name: Elixir CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        include:
          - elixir: '1.14'
            otp: '23'
          - elixir: '1.14'
            otp: '24'
          - elixir: '1.14'
            otp: '25'
            should_lint: true

          - elixir: '1.13'
            otp: '22'
          - elixir: '1.13'
            otp: '23'
          - elixir: '1.13'
            otp: '23'
          - elixir: '1.13'
            otp: '25'

          - elixir: '1.12'
            otp: '22'
          - elixir: '1.12'
            otp: '23'
          - elixir: '1.12'
            otp: '24'

          - elixir: '1.11'
            otp: '21'
          - elixir: '1.11'
            otp: '22'
          - elixir: '1.11'
            otp: '23'
          - elixir: '1.11'
            otp: '24'

          - elixir: '1.10'
            otp: '21'
          - elixir: '1.10'
            otp: '22'
          - elixir: '1.10'
            otp: '23'
          - elixir: '1.10'
            otp: '23'

          - elixir: '1.9'
            otp: '20'
          - elixir: '1.9'
            otp: '21'
          - elixir: '1.9'
            otp: '22'

          - elixir: '1.8'
            otp: '20'
          - elixir: '1.8'
            otp: '21'
          - elixir: '1.8'
            otp: '22'

          - elixir: '1.7'
            otp: '19'
          - elixir: '1.7'
            otp: '20'
          - elixir: '1.7'
            otp: '22'

          - elixir: '1.6'
            otp: '19'
          - elixir: '1.6'
            otp: '20'
          - elixir: '1.6'
            otp: '21'

          - elixir: '1.5'
            otp: '18'
          - elixir: '1.5'
            otp: '19'
          - elixir: '1.5'
            otp: '20'

          - elixir: '1.4'
            otp: '18'
          - elixir: '1.4'
            otp: '19'
          - elixir: '1.4'
            otp: '20'

          - elixir: '1.3'
            otp: '18'
          - elixir: '1.3'
            otp: '19'

          - elixir: '1.2'
            otp: '18'
          - elixir: '1.2'
            otp: '19'

          - elixir: '1.1'
            otp: '17'
          - elixir: '1.1'
            otp: '18'

          - elixir: '1.0'
            otp: '17'
          - elixir: '1.0'
            otp: '18'

    steps:
      - uses: actions/checkout@v3

      - name: Setup BEAM
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('**/mix.lock') }}

      - name: Install dependencies
        run: mix deps.get

      - name: Lint
        if: matrix.should_lint
        run: |
          mix format --check-formatted
          mix compile --warnings-as-errors
          mix dialyzer --format github

      - name: Run Tests
        run: mix test
